collections:
  notes:
    output: true
    permalink: /notes/:year/:month/:day/:path/
  replies:
    output: true
    permalink: /replies/:year/:month/:day/:path/
links:
    output: false
    permalink: /links/:year/:month/:day/:title/
